# Generated by Django 5.1.1 on 2024-09-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_message_content_remove_message_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='roomname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chatroom'),
        ),
    ]
